# Generated by Django 4.2.20 on 2025-10-01 23:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_alter_productvariant_product"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderline",
            name="order",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="lines",
                to="core.order",
            ),
        ),
    ]
